version: "3.8"
services:
    
    prs:
        build:
            context: ./PriorityRequestServer
            dockerfile: Dockerfile.prserver
        volumes:
          - type: bind
            source: $MMITSS_ROOT/mmitss/bin/corridors/Anthem/Daisy-Anthem/nojournal
            target: /nojournal
        networks:
            mmitss_br:
                ipv4_address: 10.12.6.17

    prsolver:
        build:
            context: ./PrioritySolver
            dockerfile: Dockerfile.prsolver
        volumes:
          - type: bind
            source: $MMITSS_ROOT/mmitss/bin/corridors/Anthem/Daisy-Anthem/nojournal
            target: /nojournal
        network_mode: service:prs

    tci:
        build:
            context: ./TrafficControllerInterface
            dockerfile: Dockerfile.tci
        volumes:
          - type: bind
            source: $MMITSS_ROOT/mmitss/bin/corridors/Anthem/Daisy-Anthem/nojournal
            target: /nojournal
        network_mode: service:prs

    host_bsm_decoder:
        build:
            context: ./HostBsmDecoder
            dockerfile: Dockerfile.host_bsm_decoder
        volumes:
          - type: bind
            source: $MMITSS_ROOT/mmitss/bin/corridors/Anthem/Daisy-Anthem/nojournal
            target: /nojournal
        network_mode: service:prs
        
    wmd:
        build:
            context: ./WirelessMsgDecoder
            dockerfile: Dockerfile.wmd
        volumes:
          - type: bind
            source: $MMITSS_ROOT/mmitss/bin/corridors/Anthem/Daisy-Anthem/nojournal
            target: /nojournal
        network_mode: service:prs
        
    msg_encoder:
        build:
            context: ./MsgEncoder
            dockerfile: Dockerfile.msg_encoder
        volumes:
          - type: bind
            source: $MMITSS_ROOT/mmitss/bin/corridors/Anthem/Daisy-Anthem/nojournal
            target: /nojournal
        network_mode: service:prs

    map_spat:
        build:
            context: ./MapSpatBroadcaster
            dockerfile: Dockerfile.map_spat
        volumes:
          - type: bind
            source: $MMITSS_ROOT/mmitss/bin/corridors/Anthem/Daisy-Anthem/nojournal
            target: /nojournal
        network_mode: service:prs

networks:
    mmitss_br:
        driver: bridge
        ipam:
         config:
           - subnet: 10.12.6.0/24


