version: "3.8"
services:

    daisy-gavilan:
        build:
            context: ./
            dockerfile: Dockerfile_field
        container_name: daisy-gavilan
        volumes:
          - type: bind
            source: $MMITSS_ROOT/mmitss/bin/corridors/Anthem/Daisy-Gavilan/nojournal
            target: /nojournal
        network_mode: host