version: "3.8"
services:

#    market-11th:
#        build:
#            context: ./
#        container_name: market-11th
#        volumes:
#          - type: bind
#            source: $MMITSS_ROOT/mmitss/bin/corridors/Portland_Field/market-11th/nojournal
#            target: /nojournal
#        networks:    
#            mmitss_vlan:
#                ipv4_address: 172.16.52.98    
#
    market-10th:
        build:
            context: ./
        container_name: market-10th
        volumes:
            - type: bind
              source: $MMITSS_ROOT/mmitss/bin/corridors/Portland_Field/market-10th/nojournal
              target: /nojournal
        networks:    
            mmitss_vlan:
                ipv4_address: 172.16.52.95

    market-broadway:
        build:
            context: ./
        container_name: market-broadway
        volumes:
            - type: bind
              source: $MMITSS_ROOT/mmitss/bin/corridors/Portland_Field/market-broadway/nojournal
              target: /nojournal
        networks:    
            mmitss_vlan:
                ipv4_address: 172.16.52.92        


networks:
    mmitss_vlan:
        driver: macvlan
        driver_opts:
            parent: enp4s0 
        ipam:
            config:
              - subnet: 172.16.52.0/24
